- hosts: localhost
  become_method: sudo
  become: yes
  remote_user: {{ USER }}
  vars_files:
     - roles/solr_gc_template/defaults/main.yml
  vars:
     solr_host: "{{ solr }}"
     region: "{{ region }}"
  tasks:
     - include_tasks: files/create_all_replicas.yml
       vars:
         collection: "{{ confvar.key }}"
         z: "{{ zone }}"
         s: "{{ shards }}"
         host: "{{ solr_host }}"
       with_dict: "{{ collectionConf }}"
       loop_control:
         loop_var: confvar
       when: confvar.value == 'all'
       #tags: all_shards_collection


     - include_tasks: files/create_partial_replicas.yml
       vars:
         collection: "{{ confvar.key }}"
         z: "{{ zone }}"
         s: "{{ confvar.value }}"
         host: "{{ solr_host }}"
         dict: {}
         shardNum: "{{ collectionConf[confvar.key] | length }}" #"{{ confvar.value }}"|length
       with_dict: "{{ collectionConf }}"
       loop_control:
         loop_var: confvar
       when: confvar.value != 'all'
       tags: partial_shards_collection



     #- include_tasks: files/create_partial_replicas.yml
     #  vars:
     #    collection: "{{ confvar.key }}"
     #    z: "{{ zone }}"
     #    s: "{{ shards }}"
     #    host: "{{ solr_host }}"
     #  with_dict: "{{ collectionConf }}"
     #  loop_control:
     #    loop_var: confvar
     #  when: confvar.value != 'all'
